// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

function sumOfEvens(limit){
    let temp, a = 0, b = 1, sum = 0;
    while (b < limit){
        temp = a, a = b, b += temp;
        if (b % 2===0){
        sum += b;
        }
    }
    return sum;
}
console.log(sumOfEvens(4e6))